//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attributes
    {
        public Attributes()
        {
            this.id = Guid.NewGuid().ToString();
            this.RefClasses = new HashSet<RefClasses>();
            this.RefObjects = new HashSet<RefObjects>();
        }
    
        public string id { get; set; }
        public string idTypes { get; set; }
        public string name { get; set; }
    
        public virtual Types Types { get; set; }
        public virtual ICollection<RefClasses> RefClasses { get; set; }
        public virtual ICollection<RefObjects> RefObjects { get; set; }
    }
}
