//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        public Objects()
        {
            this.id = Guid.NewGuid().ToString();
            this.Objects1 = new HashSet<Objects>();
            this.RefObjects = new HashSet<RefObjects>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string idClass { get; set; }
        public string idParent { get; set; }
        public string due { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual ICollection<Objects> Objects1 { get; set; }
        public virtual Objects Objects2 { get; set; }
        public virtual ICollection<RefObjects> RefObjects { get; set; }
    }
}
