//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefClasses
    {
        public RefClasses()
        {
            this.id = Guid.NewGuid().ToString();
        }

        public string id { get; set; }
        public string idClass { get; set; }
        public string idAttribute { get; set; }
    
        public virtual Attributes Attributes { get; set; }
        public virtual Classes Classes { get; set; }
    }
}
