//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefObjects
    {
        public RefObjects()
        {
            this.id = Guid.NewGuid().ToString();
        }

        public string id { get; set; }
        public string idObjects { get; set; }
        public string idAttributes { get; set; }
        public string value { get; set; }
    
        public virtual Attributes Attributes { get; set; }
        public virtual Objects Objects { get; set; }
    }
}
