//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Types
    {
        public Types()
        {
            this.id = Guid.NewGuid().ToString();
            this.Attributes = new HashSet<Attributes>();
        }

        public string id { get; set; }
        public string name { get; set; }

        public virtual ICollection<Attributes> Attributes { get; set; }
    }
}
